### ISSUE TITLE
UnicodeDecodeError / output not proper utf-8?

### ISSUE THREAD

**Issue by Dentosal** [minttu/tmc.py#32]
I'm trying to complete *Aalto C MOOC 2016*, but I'm getting following error with tmc.py:

    user@laptop:Module_5$ tmc te
    Something went wrong:                       
    Traceback (most recent call last):
      File "/Users/user/.local/bin/tmc", line 9, in <module>
        load_entry_point('tmc==1.0.0', 'console_scripts', 'tmc')()
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/__main__.py", line 565, in main
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/argh-0.26.1-py3.5.egg/argh/helpers.py", line 55, in dispatch
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/argh-0.26.1-py3.5.egg/argh/dispatching.py", line 174, in dispatch
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/argh-0.26.1-py3.5.egg/argh/dispatching.py", line 277, in _execute_command
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/argh-0.26.1-py3.5.egg/argh/dispatching.py", line 260, in _call
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/__main__.py", line 45, in inner
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/__main__.py", line 66, in inner
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/__main__.py", line 368, in test
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/exercise_tests/basetest.py", line 114, in run_test
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/exercise_tests/check.py", line 21, in test
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/exercise_tests/basetest.py", line 71, in run
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/ui/spinner.py", line 71, in wrapper
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/ui/spinner.py", line 66, in wrapper
      File "/Users/user/.venv_tmc/lib/python3.5/site-packages/tmc-1.0.0-py3.5.egg/tmc/exercise_tests/basetest.py", line 69, in inner
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1175: invalid start byte

Error occurs with following C code: (Sorry, I was unable to create minimal test case)

    #include <stdlib.h>
    #include <stdio.h>
    #include "base64.h"

    typedef unsigned char byte;

    /* The set of base64-encoded characters. You may use this table if you want.
     * (The last character is not part of the actual base64 set, but used for
     * padding).
     */
    const char *encoding = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";

    /* Open file named <src_file> for reading, and convert it to Base64 format,
     * which is written to file named <dst_file>.
     *
     * Returns: number of bytes in <src_file>, or -1 if there was an error,
     * for example if opening of <src_file> did not succeed.
     */
    int to_base64(const char *dst_file, const char *src_file)
    {
        FILE *fp_src = fopen(src_file, "rb");
        if (fp_src == NULL || ferror(fp_src)) {return -1;}
        FILE *fp_dst = fopen(dst_file, "wb");
        if (fp_dst == NULL || ferror(fp_dst)) {return -1;}

        byte inbytes[3] = {0, 0, 0};
        byte outbytes[4] = {0, 0, 0, 0};
        byte line[65]; // 64 + \n
        byte index = 0;
        int size = 0;

        while (1) {
            int eof = 0;
            inbytes[0]=0;inbytes[1]=0;inbytes[2]=0;
            byte count = fread(&inbytes, 1, 3, fp_src);
            size += count;
            if (feof(fp_src)) {
                eof = 1;
            }
            outbytes[0] = ((inbytes[0] & 0xfc) >> 2);
            outbytes[1] = ((inbytes[0] & 0x03) << 4) | ((inbytes[1] & 0xf0) >> 4);
            outbytes[2] = ((inbytes[1] & 0x0f) << 2) | ((inbytes[2] & 0xc0) >> 6);
            outbytes[3] = ((inbytes[2] & 0x3f));

            for (size_t i = 0; i < 4; i++) {
                if (i<=count) {
                    line[index] = encoding[outbytes[i]];
                }
                else {
                    line[index] = '=';
                }
                index += 1;
            }
            if (index == 64 || eof) {
                if (!eof) {
                    line[index] = '\n';
                }
                fwrite(line, 1, index+(eof?0:1), fp_dst);
                index = 0;
            }
            if (eof) {
                break;
            }
        }

        fclose(fp_src);
        fclose(fp_dst);
        return size;
    }

    /* Open Base64-encoded file named <src_file> for reading, and convert it
     * to regular binary format, which is written to file named <dst_file>.
     *
     * Returns: number of bytes in <src_file>, or -1 if there was an error,
     * for example if opening of <src_file> did not succeed.
     */
    int from_base64(const char *dst_file, const char *src_file)
    {
        (void) dst_file;
        (void) src_file;
        return -1;
    }

However, commenting line `inbytes[0]=0;inbytes[1]=0;inbytes[2]=0;` makes program behave incorrecly, and in that case tmc.py outputs error message, just as expected:

    user@laptop:Module_5$ tmc te
    Results:                      
    test_to_base64: [M5.03.a] to_base64 for source file 'oneline.txt' -- Your file differs from reference at byte 55. You: '5' (35), reference: '4' (34)
    test_from_base64: [M5.03.b] from_base64() for source file 'oneline.txt.ref' should return 56. You returned -1.

Submitting file that provides errors to server (using `tmc su` gives:

    Module_5-03_base64 -> TMC Server
    Submission has been sent.                       
    Results:                        
    Something went wrong :(
    -----------------------
    Running the submission failed. Exit code: 1 (did you use an exit() command?)

So it seems that this bug exists in server code as well. Is this crash intentional, or should tmc.py detect incorrect encoding and report error? (Also, I'm not sure what actually causes the error.)

Hexdump of the result file:

    user@laptop:Module_5$ hexdump -C 03_base64/test/result 
    00000000  56 47 68 70 63 79 42 6d  61 57 78 6c 49 47 68 68  |VGhpcyBmaWxlIGhh|
    00000010  63 79 42 30 5a 58 68 30  49 47 39 75 62 48 6b 67  |cyB0ZXh0IG9ubHkg|
    00000020  62 32 34 67 62 32 35 6c  49 47 78 70 62 6d 55 75  |b24gb25lIGxpbmUu|
    00000030  49 46 64 76 64 79 35 3d                           |IFdvdy5=|
    00000038

Environment:
* OS X 10.11.5
* Python 3.5.0

**Comment by minttu** [comment]
Thanks for the carefully crafted report!

I changed the UTF-8 decoding to replace invalid sequences with escaped versions of them, which should help with debugging these sort of situations instead of just giving up.
